### ISSUE TITLE
acsf-tools-ml  with a command that has options passed does not work

### ISSUE THREAD

**Issue by bkosborne** [acquia/acsf-tools#129]
I'm trying to run this:

`acsf-tools-ml pm:list --type=module --status=enabled`

But it's not handling the --type and --status options well.

I get an error ` The "--type" option does not exist.`

I guess it's thinking --type is an option for the acsf-tools-ml command. Okay, so I tried this as well:

`acsf-tools-ml -- 'pm:list --type=module --status=enabled'`

But then I get error `Command "pm:list --type=module --status=enabled" is not defined.`

**Comment by adambernstein** [comment]
The ml command must be run serverside/in a remote ssh session. Try one of the following from your remote docroot:

- `drush sfml 'pm:list --type=module --status=enabled'`
- `drush sfml 'pml --type=module --status=enabled'`

**Comment by bkosborne** [comment]
Unfortunately neither work. Do they work for you? I get error  Command "pml --type=module --status=enabled" is not defined

I am running these commands by SSHing into one of the Acquia servers, changing to docroot directory, and running the command. I specify which site to bootstrap initially as I have to always with sfml commands:

drush -l url-of-a-site-factory-site sfml 'pml --type=module --status=enabled'

**Comment by vbouchet31** [comment]
`-l` option does not make sense with `sfml` as sfml stands for "site factory multiple -l". This is the purpose of sfml to loop over the sites of the factory.
Regarding the arguments/options, it can be quite confusing. First because sfml has its own arguments/options and second because of the change since Drush 8 on how the arguments/options are processed.
The expected format is:
`drush sfml pm:list --profiles=my_profile --delay=5 "'--status=enabled' '--type=module'"`
When using sfml, pm:list is an argument of sfml. Profiles and delay are options of sfml. Arguments and options for the pm:list command must be given as a string.

**Comment by bkosborne** [comment]
Good point - I could have sworn I needed to pass a specific site to "get it started" before.

The format you provided works! Thank you!
